transform:
  outputs:
    dev:
      dataset: silver_christophe
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: ensai-2026
      threads: 1
      type: bigquery
  target: dev